// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    var height, tipStyle, width;
    width = $('body').width();
    height = $('body').height();
    window.parent.postMessage({
      action: 'resize',
      width: width,
      height: height
    }, '*');
    $('.content input').on('input', function(ev) {
      var href;
      console.log('typing');
      href = 'https://google.com/search?q=' + encodeURIComponent($.trim($(ev.currentTarget).val()));
      console.log('HREF:', href);
      return $(ev.currentTarget).closest('.question').find('a').attr('href', href);
    });
    $('.content input').on('focus', function(ev) {
      return $('.launch-quest').addClass('focused');
    });
    $('.content input').on('blur', function(ev) {
      return $('.launch-quest').removeClass('focused');
    });
    $('.question').not('.new-question-container').hover(function(ev) {
      return $('.launch-quest').removeClass('focused');
    });
    $('.question.new-question-container').hover(function(ev) {
      if ($('.question.new-question-container input').is(':focus')) {
        return $('.launch-quest').addClass('focused');
      }
    });
    tipStyle = {
      classes: 'qtip-dark qtip-shadow qtip-custom'
    };
    $('.launch-quest').qtip({
      content: {
        attr: 'data-tooltip'
      },
      position: {
        my: 'right center',
        at: 'left center'
      },
      style: tipStyle
    });
    return $('.launch-quest').on('click', function(ev) {
      return $(ev.currentTarget).qtip('hide');
    });
  });

}).call(this);
